version: '3'
services:
  app:
    image: 'portainer/portainer-ce:2.11.1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - proxy
    ports:
      - 9000:9000

volumes:
  data:

networks:
  proxy:
    external: true
